apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodes-ethereum-api
spec:
  selector:
    matchLabels:
      app: nodes-ethereum-deployment
  template:
    metadata:
      labels:
        app: nodes-ethereum-deployment
    spec:
      containers:
        - name: nodes-ethereum
          image: darchlabs/nodes-ethereum:0.0.2
          envFrom:
            - configMapRef:
                name: nodes-ethereum-config
          ports:
            - containerPort: 8888
