apiVersion: v1
kind: ConfigMap
metadata:
  name: nodes-configmap
data:
  ENVIRONMENT: dev
  API_SERVER_PORT: "6969"
  BAE_PATH_DATABASE: "data"
  NETWORKS_URL: "ethereum:capable-quick-vineyard.discover.quiknode.pro/3f240555880826d7153fe818e34bf1aef2b75e50,polygon:skilled-misty-morning.matic.discover.quiknode.pro/9c6b0efce65cc906fec0275ac85da2385a8d8359"
  REDIS_URL: "redis:6379"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodes-reporter-configmap
data:
  DATABASE_URL: "redis://redis:6379"
  SERVICE_TYPE: "nodes"
  SERVICE_URL: "http://nodes-svc:6969"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-configmap
data:
  DATABASE_FILEPATH: "./data/storage.db"
  PORT: "3030"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-reporter-configmap
data:
  DATABASE_URL: "redis://redis:6379"
  SERVICE_TYPE: "jobs"
  SERVICE_URL: "http://jobs-svc:3030"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-configmap
data:
  NODE_URL: "https://eth-goerli.g.alchemy.com/v2/iBz2dSgQkpZ4zr5aDFaW_FmTCq7SDQzi"
  INTERVAL_SECONDS: "20"
  DATABASE_FILEPATH: "./storage.db"
  PORT: "5555"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-reporter-configmap
data:
  DATABASE_URL: "redis://redis:6379"
  SERVICE_TYPE: "synchronizers"
  SERVICE_URL: "http://synchronizers-svc:5555"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
data:
  SYNCHORONIZER_API_URL: "http://synchronizers-svc:5555"
  NODE_API_URL: "http://nodes-svc:6969"
  JOB_API_URL: "http://jobs-svc:3030"
  REDIS_URL: "redis://redis:6379"
  NODE_ENV: "production"
  GOERLI_NODE_URL: "https://eth-goerli.g.alchemy.com/v2/iBz2dSgQkpZ4zr5aDFaW_FmTCq7SDQzi"
  ETHEREUM_NODE_URL: "https://eth-mainnet.g.alchemy.com/v2/aVIeYY-FMgLc3VEiNW3GsDsz5nJsidLN"

